// Mosaix example vault — the specification itself, as a Mosaix vault.
// Source of truth for the site explorer and for export_vault.py (which writes the .md files).
// Every note: path, title, type, tags, updated, summary (120–240), keywords (6–8), entities, relations, links, rev, status, body.
window.MOSAIX_VAULT = [
/* ---------- MOC ---------- */
{path:"Home.md",title:"Home",type:"moc",tags:["mosaix","moc"],updated:"2026-09-03",
 summary:"Map of content of the Mosaix example vault: the specification split into sections, keys, rules, proposals for 1.1, a synthesis and one composed document.",
 keywords:["home","map of content","index","where to start","mosaix vault","spec as vault","entry point"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§1 Purpose","§3 The note","§7 Rules","Mosaix in one page","Open questions","Mosaix for a new team","How to use these templates"],rev:"0a1f3c9e7b21",status:"sourced",
 body:"Start with [[Mosaix in one page]]. Then the sections: [[§0 Status]], [[§1 Purpose]], [[§2 Substrate]], [[§3 The note]], [[§4 Links and the graph]], [[§5 Vault structure]], [[§6 Composed documents]], [[§7 Rules]], [[§8 Out of scope]], [[§9 Host profile]], [[§10 Conformance]], [[§11 Versioning]], [[§12 Provenance]].\n\nKeys: [[key summary]], [[key keywords]], [[key entities]], [[key relations]], [[key links]], [[key rev]], [[key updated]], [[key tags]], [[key title]].\n\nRules: [[R1 Atomicity]] … [[R8 Propose, don't apply]]. What is not decided yet: [[Open questions]]. A composed document built from this vault: [[Mosaix for a new team]]. Starter templates for each note type, ready to copy into your own vault: [[How to use these templates]]."},

/* ---------- synthesis ---------- */
{path:"_synthesis/Mosaix in one page.md",title:"Mosaix in one page",type:"synthesis",tags:["mosaix","synthesis"],updated:"2026-09-03",
 summary:"One-page synthesis of the format: atomic notes with nine keys, eight rules, composed documents, and what is deliberately out of scope. Read alone before any task.",
 keywords:["synthesis","overview","tl;dr","one page","what is mosaix","summary of the spec","quick read"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"Obsidian",type:"tool"}],relations:[{from:"Mosaix Format",type:"is read by",to:"Obsidian"}],links:["§3 The note","§6 Composed documents","§7 Rules","§8 Out of scope"],rev:"5d2c88a01f44",status:"sourced",
 body:"A Mosaix vault is a folder of Markdown notes. Each note answers one question and carries nine keys above the body ([[§3 The note]]). Notes link with wikilinks; no orphans, no broken links. Content that must be read together is joined by a composed document, never copied ([[§6 Composed documents]]). Eight rules ([[§7 Rules]]): five checked from files, three commitments. Everything about producing, enriching, searching or editing notes is an implementation ([[§8 Out of scope]])."},

/* ---------- sections ---------- */
{path:"spec/§0 Status.md",title:"§0 Status",type:"section",tags:["spec","status","license"],updated:"2026-09-03",
 summary:"Status of the document: Mosaix Format 1.0, CC BY-SA 4.0, the name and version numbering are part of the specification, RFC 2119 keywords apply.",
 keywords:["status","license","cc by-sa","rfc 2119","must should may","version 1.0","name of the format"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"Creative Commons",type:"company"}],relations:[{from:"Mosaix Format",type:"licensed under",to:"CC BY-SA 4.0"}],links:["§11 Versioning","§10 Conformance"],rev:"c11e0a5f9b32",status:"sourced",
 body:"This document specifies the Mosaix Format, version 1.0. Licensed CC BY-SA 4.0. A vault may claim conformance to \"Mosaix 1.0\" only if it satisfies [[§10 Conformance]]. Versions follow [[§11 Versioning]]."},
{path:"spec/§1 Purpose.md",title:"§1 Purpose",type:"section",tags:["spec","purpose"],updated:"2026-09-03",
 summary:"Why the format exists: a machine can retrieve one note at a time and act; a person can read many notes as one document; nothing is silently lost or overwritten.",
 keywords:["purpose","why","goal","machine and human","one note at a time","nothing lost","bounded context"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","§6 Composed documents","R6 Record, don't resolve"],rev:"e7a4b2c30d19",status:"sourced",
 body:"Three goals. A machine retrieves one note ([[§3 The note]]) and has enough context to act. A person reads many notes as one document ([[§6 Composed documents]]). Contradictions are recorded ([[R6 Record, don't resolve]]), superseded notes are marked, automated writes are proposed. The format is deliberately small."},
{path:"spec/§2 Substrate.md",title:"§2 Substrate",type:"section",tags:["spec","substrate","markdown"],updated:"2026-09-03",
 summary:"The substrate is plain text: UTF-8 Markdown files, optional YAML frontmatter, wikilinks resolved by basename, embeds with ![[ ]], tags in body or frontmatter.",
 keywords:["markdown","frontmatter","wikilink","embed","transclusion","basename","plain files","utf-8"],
 entities:[{name:"CommonMark",type:"document"},{name:"Obsidian",type:"tool"}],relations:[{from:"Mosaix Format",type:"builds on",to:"CommonMark"}],links:["§9 Host profile","§4 Links and the graph"],rev:"9f0d3b7ae255",status:"sourced",
 body:"Notes are `.md` files in CommonMark. A wikilink (the target title in double square brackets) resolves by the target's basename, case-sensitive, anywhere in the vault ([[§4 Links and the graph]]). Any tool that reads Markdown reads a Mosaix vault; Obsidian is the reference host ([[§9 Host profile]]), not a dependency."},
{path:"spec/§3 The note.md",title:"§3 The note",type:"section",tags:["spec","note","frontmatter","core"],updated:"2026-09-03",
 summary:"The note is the tile: it answers one question and carries the CORE frontmatter of nine keys; the body is never touched by metadata operations; aliases are allowed if declared.",
 keywords:["the note","tile","core keys","nine keys","frontmatter core","one question","byte identical body","aliases"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[{from:"§3 The note",type:"defines",to:"CORE frontmatter"}],links:["key summary","key keywords","key entities","key relations","key links","key rev","key updated","key tags","key title","R1 Atomicity"],rev:"1b6e4d8c0a73",status:"sourced",
 body:"A note answers one question ([[R1 Atomicity]]). CORE keys: [[key title]], [[key updated]], [[key tags]], [[key summary]], [[key keywords]], [[key entities]], [[key relations]], [[key links]], [[key rev]]. Italian key names used by earlier vaults (mcp_entita, mcp_relazioni, mcp_collegamenti, mcp_rev) are accepted as aliases. Any process that rewrites frontmatter MUST leave the body byte-identical."},
{path:"spec/§4 Links and the graph.md",title:"§4 Links and the graph",type:"section",tags:["spec","links","graph"],updated:"2026-09-03",
 summary:"Every note needs an incoming link; every wikilink must resolve; links mirrors outbound links; the graph is derived from files and is never the source of truth.",
 keywords:["orphan","broken link","incoming link","graph derived","wikilink resolution","connectedness","source of truth"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["R3 Connectedness","key links","§2 Substrate"],rev:"3c9a17f2e6b0",status:"sourced",
 body:"A note with no incoming link is an orphan: a conformance error ([[R3 Connectedness]]). An unresolved wikilink is an error. [[key links]] is the machine-readable mirror of outbound links. Notes, entities, relations and wikilinks form the graph; the graph is derived, never authoritative."},
{path:"spec/§5 Vault structure.md",title:"§5 Vault structure",type:"section",tags:["spec","structure","folders"],updated:"2026-09-03",
 summary:"Free layout with three reserved folders: _meta for governance, _synthesis for stand-alone syntheses, _inbox for material not yet turned into notes; plus the ledger and the meta note.",
 keywords:["folders","_meta","_synthesis","_inbox","_private","open questions ledger","meta note","reading order"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"Open questions",type:"document"}],relations:[],links:["Open questions","Conventions","Mosaix in one page","R4 Declared taxonomy"],rev:"7e2f50b4d1c8",status:"sourced",
 body:"Folders are free; numbered prefixes are a reading order. Reserved: `_meta/` (this vault's [[Conventions]] and [[Open questions]]), `_synthesis/` (see [[Mosaix in one page]]), `_inbox/` (nothing there counts). The meta note declares folders, reliability convention, domain keys and the tag taxonomy ([[R4 Declared taxonomy]])."},
{path:"spec/§6 Composed documents.md",title:"§6 Composed documents",type:"section",tags:["spec","document","composition"],updated:"2026-09-03",
 summary:"Defines the note type document that joins atomic notes into one readable document without duplicating them: fragments in reading order, optional pool and layout.",
 keywords:["composed document","type document","fragments","view over notes","transclusion","reading order","no duplication"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[{from:"§6 Composed documents",type:"depends on",to:"§3 The note"}],links:["R5 Composition over duplication","Mosaix for a new team","§3 The note"],rev:"91be7f0a3c44",status:"sourced",
 body:"Atomic notes are for machines; people read documents. A note with `type: document` lists `fragments` in reading order, optionally `pool` and `layout`. The fragments stay separate; the document is the view ([[R5 Composition over duplication]]). Example in this vault: [[Mosaix for a new team]]."},
{path:"spec/§7 Rules.md",title:"§7 Rules",type:"section",tags:["spec","rules"],updated:"2026-09-03",
 summary:"The eight rules of a conforming vault: five verifiable from files (R1–R5) and three process commitments the meta note makes (R6–R8).",
 keywords:["rules","r1 to r8","eight rules","commitments","verifiable","conformance rules","process rules"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["R1 Atomicity","R2 Self-description","R3 Connectedness","R4 Declared taxonomy","R5 Composition over duplication","R6 Record, don't resolve","R7 Supersede, don't delete","R8 Propose, don't apply"],rev:"b04c6e1d9a57",status:"sourced",
 body:"Verifiable: [[R1 Atomicity]], [[R2 Self-description]], [[R3 Connectedness]], [[R4 Declared taxonomy]], [[R5 Composition over duplication]]. Commitments: [[R6 Record, don't resolve]], [[R7 Supersede, don't delete]], [[R8 Propose, don't apply]]."},
{path:"spec/§8 Out of scope.md",title:"§8 Out of scope",type:"section",tags:["spec","scope"],updated:"2026-09-03",
 summary:"What the specification does not define: enrichment, ingest, retrieval and ranking, editors, agent exposure and synchronisation, graph visualisation. Implementations compete there.",
 keywords:["out of scope","not defined","implementations","enrichment","retrieval","editors","mcp tools","hand-made vault"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"Obsidian",type:"tool"}],relations:[],links:["§1 Purpose","§10 Conformance"],rev:"d58a2c7f0e91",status:"sourced",
 body:"Not defined: how summary and keys are generated; how documents become notes; how notes are retrieved; how composed documents are edited; how the vault is exposed to agents or synced; how the graph is drawn. A vault produced by hand can be fully conformant ([[§10 Conformance]])."},
{path:"spec/§9 Host profile.md",title:"§9 Host profile",type:"section",tags:["spec","obsidian","host"],updated:"2026-09-03",
 summary:"Obsidian is the reference host: its wikilink, embed, tag and frontmatter handling match the substrate; Dataview, Bases, Canvas and callouts are outside the format and never required.",
 keywords:["obsidian","host application","dataview","bases","canvas","callouts","logseq foam dendron zettlr","not a dependency"],
 entities:[{name:"Obsidian",type:"tool"},{name:"Logseq",type:"tool"},{name:"Foam",type:"tool"}],relations:[{from:"Obsidian",type:"is reference host of",to:"Mosaix Format"}],links:["§2 Substrate"],rev:"2a7d9e4b6c10",status:"sourced",
 body:"Obsidian matches [[§2 Substrate]] exactly. Host features (Dataview, `.base`, Canvas, callouts) are views, not content, and MUST NOT be required. `.obsidian/` is host state; `workspace.json` should stay out of version control. Other hosts: Logseq, Foam, Dendron, Zettlr."},
{path:"spec/§10 Conformance.md",title:"§10 Conformance",type:"section",tags:["spec","conformance","checker"],updated:"2026-09-03",
 summary:"A vault is Mosaix 1.0 conformant when the file checks report zero errors: frontmatter, key ranges, entity coverage, resolving links, no orphans, a MOC, a ledger, a meta note; warnings allowed.",
 keywords:["conformance","checker","audit_reference.py","errors and warnings","zero errors","conformant vault","exit code"],
 entities:[{name:"audit_reference.py",type:"tool"}],relations:[{from:"audit_reference.py",type:"verifies",to:"§10 Conformance"}],links:["§7 Rules","R2 Self-description","R3 Connectedness"],rev:"6f1b3d8a2e07",status:"sourced",
 body:"Errors: missing frontmatter or core keys, summary outside 120–240, keywords outside 6–8, entity coverage under 80%, unresolved links, orphans, no MOC, no ledger, no meta note, a document with fewer than two fragments. Warnings: undeclared tags or keys, stale rev, no reliability marker. The reference checker is `audit_reference.py`."},
{path:"spec/§11 Versioning.md",title:"§11 Versioning",type:"section",tags:["spec","versioning"],updated:"2026-09-03",
 summary:"Versions follow MAJOR.MINOR.PATCH: a MINOR version adds optional keys, note types or warnings and never breaks a conformant vault; a MAJOR version may; vaults state their target version.",
 keywords:["versioning","semver","minor never breaks","major may break","mosaix 1.0 key","target version","1.1"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§0 Status","Open questions"],rev:"4e8c2a9f7d63",status:"sourced",
 body:"Vaults SHOULD state `mosaix: \"1.0\"` in their meta note. What 1.1 may add is tracked in [[Open questions]]."},
{path:"spec/§12 Provenance.md",title:"§12 Provenance",type:"section",tags:["spec","provenance","history"],updated:"2026-09-03",
 summary:"Where the format comes from: three production vaults (code documentation, industrial market intelligence, education marketing), measured for the conventions a machine could rely on.",
 keywords:["provenance","origin","three vaults","extracted from practice","history of the format","acknowledgements"],
 entities:[{name:"Boom Digital",type:"company"},{name:"SLIM",type:"project"}],relations:[{from:"Mosaix Format",type:"is a format of",to:"SLIM"},{from:"Boom Digital",type:"maintains",to:"Mosaix Format"}],links:["§1 Purpose","SLIM Vault Format"],rev:"8d3f5b1c2a96",status:"sourced",
 body:"The two-axis reliability model, the open-questions ledger and supersede-don't-delete come from working with sources of different dates. The composed-document type comes from a vault of good atomic notes being unreadable by the people who needed it. Earlier working name: [[SLIM Vault Format]]."},

/* ---------- keys ---------- */
{path:"keys/key summary.md",title:"key summary",type:"key",tags:["key","core","summary"],updated:"2026-09-03",
 summary:"summary is one declarative sentence of 120–240 characters saying what the note contains; it never repeats the title and is the first thing a machine reads.",
 keywords:["summary","120-240 characters","declarative sentence","first thing read","preview","dense signal","not the title"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","key keywords"],rev:"a1b2c3d4e5f6",status:"sourced",
 body:"Written for a reader who has not opened the note. MUST NOT begin with \"This note…\". Pairs with [[key keywords]] for retrieval. Defined in [[§3 The note]]."},
{path:"keys/key keywords.md",title:"key keywords",type:"key",tags:["key","core","keywords"],updated:"2026-09-03",
 summary:"keywords lists six to eight lowercase terms describing how someone would search for the note: synonyms, spoken phrasings, questions; it must not duplicate tags.",
 keywords:["keywords","6 to 8 terms","synonyms","how to search","recall","spoken language","not tags"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","key tags"],rev:"b2c3d4e5f6a1",status:"sourced",
 body:"Recall on synonyms. Distinct from [[key tags]], which are taxonomy. Defined in [[§3 The note]]."},
{path:"keys/key entities.md",title:"key entities",type:"key",tags:["key","core","graph"],updated:"2026-09-03",
 summary:"entities lists the named things in a note as {name, type} with a closed set of types: person, company, product, project, tool, place, document, event, or declared extras.",
 keywords:["entities","mcp_entita","named things","entity types","closed set","person company product","event"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","key relations","Proposal entity registry"],rev:"c3d4e5f6a1b2",status:"sourced",
 body:"Max 12 per note. Types are closed; a vault may declare more in its meta note. Entities are matched by name today; see [[Proposal entity registry]]. Relations between them: [[key relations]]."},
{path:"keys/key relations.md",title:"key relations",type:"key",tags:["key","core","graph"],updated:"2026-09-03",
 summary:"relations lists typed links between named entities as {from, type, to}; in 1.0 the relation type is a free short verb phrase, which a proposal for 1.1 wants to close.",
 keywords:["relations","mcp_relazioni","typed links","from type to","graph edges","verb phrase","relation vocabulary"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","key entities","Proposal relation vocabulary"],rev:"d4e5f6a1b2c3",status:"sourced",
 body:"Edges between [[key entities]] entries. Free `type` in 1.0 (owns, depends on, supplies…). Closed vocabulary under discussion: [[Proposal relation vocabulary]]."},
{path:"keys/key links.md",title:"key links",type:"key",tags:["key","core","links"],updated:"2026-09-03",
 summary:"links is the machine-readable list of wikilink targets a note points to; each entry must resolve to an existing note; it may be a subset of the body's links.",
 keywords:["collegamenti","outbound links","machine readable links","wikilink targets","must resolve","closed list"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§4 Links and the graph","R3 Connectedness"],rev:"e5f6a1b2c3d4",status:"sourced",
 body:"Mirror of the body's wikilinks. Unresolved targets are errors ([[R3 Connectedness]]). Defined in [[§4 Links and the graph]]."},
{path:"keys/key rev.md",title:"key rev",type:"key",tags:["key","core","staleness"],updated:"2026-09-03",
 summary:"rev is a 12-hex hash of the body at the time entities, relations and links were computed; a mismatch with the current body means the metadata is stale and must be recomputed.",
 keywords:["rev","revision hash","staleness","metadata stale","12 hex","closing the loop","body changed"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","R8 Propose, don't apply"],rev:"f6a1b2c3d4e5",status:"sourced",
 body:"Written by the system. Lets a reviewer see whether a proposal was made against the current body ([[R8 Propose, don't apply]])."},
{path:"keys/key updated.md",title:"key updated",type:"key",tags:["key","core","time"],updated:"2026-09-03",
 summary:"updated is the date of the last substantive change to the note, in YYYY-MM-DD; it drives staleness of the note itself, not of a fact inside it, which 1.1 may add as as_of.",
 keywords:["updated","date","last change","yyyy-mm-dd","staleness","aggiornato alias","as_of"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","Proposal origin and as_of"],rev:"a7b8c9d0e1f2",status:"sourced",
 body:"Alias `aggiornato` is recognised. The date of a fact inside the note is a different thing: [[Proposal origin and as_of]]."},
{path:"keys/key tags.md",title:"key tags",type:"key",tags:["key","core","taxonomy"],updated:"2026-09-03",
 summary:"tags carry the taxonomy of the vault; every tag in use must be declared in the meta note, otherwise the checker raises a warning; tags in body and frontmatter are equivalent.",
 keywords:["tags","taxonomy","declared tags","meta note","warning undeclared","hashtag","filter"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","R4 Declared taxonomy","Conventions"],rev:"b8c9d0e1f2a3",status:"sourced",
 body:"Declared in [[Conventions]] for this vault. Rule: [[R4 Declared taxonomy]]."},
{path:"keys/key title.md",title:"key title",type:"key",tags:["key","core"],updated:"2026-09-03",
 summary:"title is the name of the node; it may be derived from the filename; wikilinks resolve by basename, so the title and the filename should agree until a stable id exists.",
 keywords:["title","name of the node","filename","basename","derived","stable id","rename"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§3 The note","Proposal stable id"],rev:"c9d0e1f2a3b4",status:"sourced",
 body:"Renaming a note breaks links resolved by basename; hosts mask this. A stable identifier is proposed: [[Proposal stable id]]."},

/* ---------- rules ---------- */
{path:"rules/R1 Atomicity.md",title:"R1 Atomicity",type:"rule",tags:["rule","verifiable"],updated:"2026-09-03",
 summary:"One note answers one question; if a draft answers two it is two notes; the body length is not constrained, the scope is; a question field is proposed to make this checkable.",
 keywords:["atomicity","one question","scope not length","split notes","atomic note","checkable","question field"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","§3 The note","Proposal question field"],rev:"11aa22bb33cc",status:"sourced",
 body:"Today atomicity is a judgement. [[Proposal question field]] would record the question a note answers and make R1 verifiable."},
{path:"rules/R2 Self-description.md",title:"R2 Self-description",type:"rule",tags:["rule","verifiable"],updated:"2026-09-03",
 summary:"Every note carries the CORE frontmatter; a note without it is not a tile; the checker reports missing keys, summary length and keyword count per note.",
 keywords:["self-description","core keys present","missing frontmatter","summary length","keyword count","per note errors"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","§3 The note","§10 Conformance"],rev:"22bb33cc44dd",status:"sourced",
 body:"Verified by [[§10 Conformance]]."},
{path:"rules/R3 Connectedness.md",title:"R3 Connectedness",type:"rule",tags:["rule","verifiable"],updated:"2026-09-03",
 summary:"No orphans and no broken links: every note has at least one incoming wikilink and every wikilink resolves; the graph must be walkable from the map of content.",
 keywords:["connectedness","no orphans","broken links","incoming link","walkable graph","reachable from moc"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","§4 Links and the graph"],rev:"33cc44dd55ee",status:"sourced",
 body:"See [[§4 Links and the graph]]."},
{path:"rules/R4 Declared taxonomy.md",title:"R4 Declared taxonomy",type:"rule",tags:["rule","verifiable"],updated:"2026-09-03",
 summary:"Every tag and every domain key is declared in the meta note, with allowed values; a tag used but not declared is a warning; the taxonomy is updated in the same change that adds the tag.",
 keywords:["declared taxonomy","meta note","tag declared","domain keys","allowed values","warning","same change"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","§5 Vault structure","Conventions"],rev:"44dd55ee66ff",status:"sourced",
 body:"This vault declares its tags in [[Conventions]]."},
{path:"rules/R5 Composition over duplication.md",title:"R5 Composition over duplication",type:"rule",tags:["rule","verifiable"],updated:"2026-09-03",
 summary:"Content that must be read together is joined with a composed document or a synthesis, never copied; duplicated prose is the failure this rule prevents.",
 keywords:["composition","no duplication","composed document","synthesis","copy paste","single source","join not copy"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","§6 Composed documents","Mosaix for a new team"],rev:"55ee66ff77aa",status:"sourced",
 body:"Mechanism: [[§6 Composed documents]]. Example: [[Mosaix for a new team]]."},
{path:"rules/R6 Record, don't resolve.md",title:"R6 Record, don't resolve",type:"rule",tags:["rule","commitment"],updated:"2026-09-03",
 summary:"A contradiction between notes is entered in the open-questions ledger with both versions, dates, sources and the practical consequence; nobody picks a winner silently.",
 keywords:["record don't resolve","contradiction","open questions ledger","both versions","consequence","no silent winner","dates and sources"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","Open questions","§5 Vault structure"],rev:"66ff77aa88bb",status:"sourced",
 body:"Numbers, prices, dates and commitments to third parties are never chosen on behalf of the owner. Ledger of this vault: [[Open questions]]."},
{path:"rules/R7 Supersede, don't delete.md",title:"R7 Supersede, don't delete",type:"rule",tags:["rule","commitment"],updated:"2026-09-03",
 summary:"A note that is no longer valid is marked superseded and left in place because other notes link to it; deletion is reserved for notes created in error.",
 keywords:["supersede","don't delete","superseded note","status superseded","kept in place","links preserved","archive"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","SLIM Vault Format"],rev:"77aa88bb99cc",status:"sourced",
 body:"Example in this vault: [[SLIM Vault Format]], the working name before Mosaix."},
{path:"rules/R8 Propose, don't apply.md",title:"R8 Propose, don't apply",type:"rule",tags:["rule","commitment"],updated:"2026-09-03",
 summary:"Any automated process writes to a branch, a pull request or a staging area a person reviews; automated processes never write to the main line; rev shows what the proposal was made against.",
 keywords:["propose don't apply","branch","pull request","review queue","human merges","automated writes","staging"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"git",type:"tool"}],relations:[],links:["§7 Rules","key rev"],rev:"88bb99ccaadd",status:"sourced",
 body:"Mechanism that makes review possible: [[key rev]]."},

/* ---------- meta ---------- */
{path:"_meta/Conventions.md",title:"Conventions",type:"meta",tags:["1.1","checker","commitment","composed-document","composition","conformance","conventions","core","document","folders","frontmatter","graph","guide","history","host","key","keywords","ledger","license","links","markdown","meta","moc","mosaix","note","obsidian","onboarding","proposal","provenance","purpose","rule","rules","scope","spec","staleness","status","structure","substrate","summary","superseded","synthesis","taxonomy","template","time","verifiable","versioning"],updated:"2026-09-05",
 summary:"Meta note of this vault: folder contract, reliability convention (status key), declared tags and entity types, target version mosaix 1.0, and who maintains it.",
 keywords:["conventions","meta note","folder contract","reliability convention","declared tags","status","maintainer","mosaix 1.0"],
 entities:[{name:"Boom Digital",type:"company"}],relations:[],links:["§5 Vault structure","R4 Declared taxonomy","Open questions"],rev:"99ccaaddbbee",status:"sourced",
 body:"mosaix: \"1.0\". Folders: `spec/` sections, `keys/` core keys, `rules/`, `proposals/` for 1.1, `_meta/`, `_synthesis/`, `_docs/` composed documents, `templates/` a starter template for each note type. Reliability: frontmatter key `status` with values sourced · to-confirm · superseded. Tags declared: the `tags` list of this note is the taxonomy of the vault (46 tags). Entity types: the eight of §3. Maintainer: Boom Digital."},
{path:"_meta/Open questions.md",title:"Open questions",type:"ledger",tags:["meta","ledger","1.1"],updated:"2026-09-03",
 summary:"Ledger of what is not decided: five proposals for 1.1 (stable id, question field, relation vocabulary, entity registry, origin and as_of), each with the consequence of choosing.",
 keywords:["open questions","ledger","undecided","proposals 1.1","stable id","question field","relation vocabulary","entity registry"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Proposal stable id","Proposal question field","Proposal relation vocabulary","Proposal entity registry","Proposal origin and as_of","R6 Record, don't resolve"],rev:"aaddbbeeccff",status:"sourced",
 body:"Kept per [[R6 Record, don't resolve]]. Open: [[Proposal stable id]] · [[Proposal question field]] · [[Proposal relation vocabulary]] · [[Proposal entity registry]] · [[Proposal origin and as_of]]. Each is marked `status: to-confirm` until decided."},

/* ---------- proposals (to confirm) ---------- */
{path:"proposals/Proposal stable id.md",title:"Proposal stable id",type:"proposal",tags:["proposal","1.1"],updated:"2026-09-03",
 summary:"Add an immutable id key so links survive renames; wikilinks keep resolving by basename for people, tools resolve by id; consequence: every existing note needs an id backfilled once.",
 keywords:["stable id","immutable identifier","rename safe","uuid","backfill","links survive rename","1.1"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Open questions","key title"],rev:"bbeeccffdd11",status:"to-confirm",
 body:"Open. Decision affects [[key title]] and every checker. Recorded in [[Open questions]]."},
{path:"proposals/Proposal question field.md",title:"Proposal question field",type:"proposal",tags:["proposal","1.1"],updated:"2026-09-03",
 summary:"Add a question key recording the single question a note answers; makes R1 verifiable and retrieval by intent deterministic; consequence: notes that cannot fill it must be split.",
 keywords:["question field","risponde a","intent retrieval","atomicity check","split notes","purpose of the note","1.1"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Open questions","R1 Atomicity"],rev:"ccffdd112233",status:"to-confirm",
 body:"Open. Would make [[R1 Atomicity]] a file check. Recorded in [[Open questions]]."},
{path:"proposals/Proposal relation vocabulary.md",title:"Proposal relation vocabulary",type:"proposal",tags:["proposal","1.1"],updated:"2026-09-03",
 summary:"Close the relation type to a vocabulary declared per vault with explicit direction, so a query like everything that depends on X is deterministic; consequence: free phrases must be mapped.",
 keywords:["relation vocabulary","closed relation types","direction","deterministic query","depends on","mapping free phrases","1.1"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Open questions","key relations"],rev:"dd112233ee44",status:"to-confirm",
 body:"Open. Changes [[key relations]]. Recorded in [[Open questions]]."},
{path:"proposals/Proposal entity registry.md",title:"Proposal entity registry",type:"proposal",tags:["proposal","1.1"],updated:"2026-09-03",
 summary:"One note per canonical entity with a list of aliases, and entities pointing to the canonical name, so Meta, Meta Ads and Facebook Ads are one entity for the machine.",
 keywords:["entity registry","canonical entity","aliases","entity note","deduplicate entities","one entity many names","1.1"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Open questions","key entities"],rev:"ee4455ff6677",status:"to-confirm",
 body:"Open. Changes [[key entities]]. Recorded in [[Open questions]]."},
{path:"proposals/Proposal origin and as_of.md",title:"Proposal origin and as_of",type:"proposal",tags:["proposal","1.1"],updated:"2026-09-03",
 summary:"Add origin (human, distilled, observed) as a third axis, where a fact comes from, and as_of, the date the fact was true, distinct from updated; validated in production by a reporting system.",
 keywords:["origin","provenance axis","as_of","date of the fact","human distilled observed","third axis","1.1"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Open questions","key updated"],rev:"ff66778899aa",status:"to-confirm",
 body:"Open. Complements [[key updated]]. Recorded in [[Open questions]]."},

/* ---------- superseded ---------- */
{path:"_meta/SLIM Vault Format.md",title:"SLIM Vault Format",type:"superseded",tags:["meta","superseded"],updated:"2026-09-03",
 summary:"Working name of the specification before it was named Mosaix on 3 September 2026; kept in place because the provenance section and the changelog link to it; superseded, not deleted.",
 keywords:["slim vault format","old name","working title","renamed","superseded","provenance","changelog"],
 entities:[{name:"SLIM",type:"project"}],relations:[{from:"SLIM Vault Format",type:"superseded by",to:"Mosaix Format"}],links:["§12 Provenance","R7 Supersede, don't delete"],rev:"1122aabb33cc",status:"superseded",
 body:"Superseded by Mosaix Format ([[§12 Provenance]]). Kept per [[R7 Supersede, don't delete]]."},

/* ---------- composed document ---------- */
{path:"_docs/Mosaix for a new team.md",title:"Mosaix for a new team",type:"document",tags:["composed-document","onboarding"],updated:"2026-09-03",
 summary:"Composed document for someone joining a team that uses Mosaix: purpose, the note, the three commitments and what is out of scope, assembled from six notes without copying them.",
 keywords:["onboarding","new team member","composed document example","read in ten minutes","fragments","assembled","document"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§1 Purpose","§3 The note","R6 Record, don't resolve","R7 Supersede, don't delete","R8 Propose, don't apply","§8 Out of scope"],rev:"2233bbcc44dd",status:"sourced",
 fragments:["§1 Purpose","§3 The note","R6 Record, don't resolve","R7 Supersede, don't delete","R8 Propose, don't apply","§8 Out of scope"],
 body:"Read the six fragments in order. The document is only the view; each fragment stays its own note."},

/* ---------- templates ---------- */
{path:"templates/Template — note.md",title:"Template — note",type:"template",tags:["template"],updated:"2026-09-05",
 summary:"Starter CORE frontmatter and body for an ordinary Mosaix note, with Obsidian Templates placeholders for title and date, ready to fill in before linking it into the vault.",
 keywords:["starter template","ordinary note","core frontmatter","obsidian templates plugin","title and date placeholder","fill in before linking","one question one answer"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"Obsidian",type:"tool"}],relations:[],links:["§3 The note","R1 Atomicity","key rev"],rev:"aa11bb22cc33",status:"sourced",
 body:"Copy this file to start an ordinary note ([[§3 The note]]). One question. Answer it. Name the source.\n\n- **One question.** Write the single thing this note answers; if you need \"and\", split it into two notes ([[R1 Atomicity]]).\n- **Answer it.** The body is the answer, nothing more; length is not the constraint, scope is.\n- **Name the source.** Say where the fact comes from, then move `status` from `to-confirm` to `sourced`.\n- **Link it in.** Add at least one wikilink to an existing note so this note is not an orphan; `rev` closes the loop once metadata is computed ([[key rev]]).\n\nReplace the frontmatter above with this when you copy the template. `{{title}}` and `{{date:YYYY-MM-DD}}` are Obsidian Templates placeholders; fill them in by hand if you are not using Obsidian.\n\n```yaml\n---\ntitle: {{title}}\nupdated: {{date:YYYY-MM-DD}}\ntags: []\nstatus: to-confirm\nsummary: \"\"\nkeywords: []\nentities: []\nrelations: []\nlinks: []\nrev: \"\"\n---\n```"},
{path:"templates/Template — MOC.md",title:"Template — MOC",type:"moc",tags:["template"],updated:"2026-09-05",
 summary:"Starter frontmatter and body for a map of content: one paragraph naming an area of the vault followed by the wikilinks to its notes, the entry point a reader opens first.",
 keywords:["starter template","map of content","moc structure","one paragraph per area","entry point","reading order","links after prose"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["Home","§5 Vault structure","R3 Connectedness"],rev:"bb22cc33dd44",status:"sourced",
 body:"Copy this file to start a map of content ([[§5 Vault structure]]). Structure: one paragraph per area, then the links.\n\n- **One paragraph per area.** Name the area in a sentence or two: what it covers, why it matters, where to start.\n- **Then the links.** After the paragraph, list the wikilinks to the notes in that area, in reading order.\n- **Stay reachable.** Every note in the vault should be reachable from a MOC, directly or through another MOC ([[R3 Connectedness]]).\n- See [[Home]] in this vault for a working MOC.\n\nReplace the frontmatter above with this when you copy the template:\n\n```yaml\n---\ntitle: {{title}}\nupdated: {{date:YYYY-MM-DD}}\ntags: []\ntype: moc\nstatus: sourced\nsummary: \"\"\nkeywords: []\nentities: []\nrelations: []\nlinks: []\nrev: \"\"\n---\n```"},
{path:"templates/Template — synthesis.md",title:"Template — synthesis",type:"synthesis",tags:["template"],updated:"2026-09-05",
 summary:"Starter frontmatter and body for a synthesis note that condenses an area of the vault into one page a reader or a machine can consume alone, linking every note it summarises.",
 keywords:["starter template","synthesis note","one page summary","stand-alone context","links every note","condense an area","read alone"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§5 Vault structure","Mosaix in one page","R5 Composition over duplication"],rev:"cc33dd44ee55",status:"sourced",
 body:"Copy this file to start a synthesis note that lives in `_synthesis/` ([[§5 Vault structure]]). It must link every note it summarises.\n\n- **Condense one area** into a text a reader or a machine can consume alone, before any task in that area.\n- **Link every note it summarises.** A synthesis that leaves a note out is incomplete, not concise ([[R5 Composition over duplication]]).\n- **It is not the source.** When the synthesis disagrees with a note, the note wins; the synthesis is stale.\n- See [[Mosaix in one page]] in this vault for a working synthesis.\n\nReplace the frontmatter above with this when you copy the template:\n\n```yaml\n---\ntitle: {{title}}\nupdated: {{date:YYYY-MM-DD}}\ntags: []\ntype: synthesis\nstatus: sourced\nsummary: \"\"\nkeywords: []\nentities: []\nrelations: []\nlinks: []\nrev: \"\"\n---\n```"},
{path:"templates/Template — document.md",title:"Template — document",type:"template",tags:["template"],updated:"2026-09-05",
 summary:"Starter frontmatter for a composed document: fragments in reading order, an optional pool of candidates and a free-form layout map for the cover, sections and page format.",
 keywords:["starter template","composed document","fragments in order","optional pool","layout map","cover and sections","view over notes"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§6 Composed documents","Mosaix for a new team","R5 Composition over duplication"],rev:"dd44ee55ff66",status:"sourced",
 body:"Copy this file to start a composed document ([[§6 Composed documents]]). The fragments stay atomic and separate; the document is only the view.\n\n- **`fragments`** is the ordered list of note titles that make up the document, in reading order; a document needs at least two, and each must resolve.\n- **`pool`** is optional: candidate notes you considered but did not include.\n- **`layout`** is optional and free-form: cover, page format, sections, and which of each fragment's frontmatter to show.\n- **Never copy.** Content that must be read together is joined here, never duplicated into the fragments ([[R5 Composition over duplication]]).\n- See [[Mosaix for a new team]] in this vault for a working composed document.\n\nA blank document starts with an empty `fragments` and `pool`; fill them in as you choose fragments, then add `layout` if you want presentation hints. Replace the frontmatter above with this when you copy the template:\n\n```yaml\n---\ntitle: {{title}}\nupdated: {{date:YYYY-MM-DD}}\ntags: []\ntype: document\nstatus: sourced\nsummary: \"\"\nkeywords: []\nentities: []\nrelations: []\nlinks: []\nfragments: []\npool: []\nlayout:\n  cover: {title: '', subtitle: '', date: {{date:YYYY-MM-DD}}}\n  page: A4\n  sections:\n    - {title: '', fragments: []}\n  show: [summary, status]\nrev: \"\"\n---\n```"},
{path:"templates/Template — Conventions.md",title:"Template — Conventions",type:"template",tags:["template"],updated:"2026-09-05",
 summary:"Starter frontmatter for a vault's meta note: the folder contract, the reliability convention, declared tags, domain keys, aliases, entity and relation types, and maintainers.",
 keywords:["starter template","meta note","folder contract","reliability convention","declared taxonomy","domain keys","maintainers"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§5 Vault structure","R4 Declared taxonomy","Conventions"],rev:"ee55ff66aa77",status:"sourced",
 body:"Copy this file to start the meta note of your own vault ([[§5 Vault structure]]). It is the one note that states the vault's own rules.\n\n- **Folder contract.** Which question each folder answers.\n- **Reliability convention.** Which key or marker carries axis A: this vault uses `status`.\n- **Declared taxonomy.** Every tag in use, in one list; a tag used but not declared is a warning ([[R4 Declared taxonomy]]).\n- **Domain keys, aliases, entity and relation types, maintainers.** Anything your vault adds beyond CORE.\n- See [[Conventions]] in this vault for a working meta note.\n\nReplace the frontmatter above with this when you copy the template, then fill in the example values for your own vault:\n\n```yaml\n---\ntitle: {{title}}\nupdated: {{date:YYYY-MM-DD}}\ntags: [moc, meta, ledger, player, market]\nstatus: sourced\nsummary: \"\"\nkeywords: []\nentities: []\nrelations: []\nlinks: []\nmosaix: \"1.0\"\nfolders: {01-Company: who they are, 02-Market: where they sell}\nreliability: {key: status, values: [sourced, to-confirm, superseded]}\ndomain_keys: {client: string, country: ISO-3166 alpha-2}\naliases: {aggiornato: updated}\nentity_types: [department, regulation]\nrelation_types: [owns, supplies, competes with, depends on]\npayload: [exports/]\nmaintainers: [{name: '', area: ''}]\nrev: \"\"\n---\n```"},
{path:"templates/Template — Open questions.md",title:"Template — Open questions",type:"ledger",tags:["template"],updated:"2026-09-05",
 summary:"Starter frontmatter and entry structure for the open-questions ledger: the question, the competing versions with dates and sources, the consequence, and who resolves it.",
 keywords:["starter template","open questions ledger","competing versions","dates and sources","practical consequence","who resolves it","record don't resolve"],
 entities:[{name:"Mosaix Format",type:"project"}],relations:[],links:["§7 Rules","Open questions","R6 Record, don't resolve"],rev:"ff66aa77bb88",status:"sourced",
 body:"Copy this file to start the open-questions ledger, canonically `_meta/Open questions.md`, part of the vault's rules ([[§7 Rules]]). One entry per contradiction or unknown.\n\n- **The question.** What is not yet known or is contradictory.\n- **The competing versions**, each with its date and its source.\n- **The consequence.** What changes in practice depending on which version wins.\n- **The owner.** Who is expected to resolve it.\n- Nobody picks a winner silently ([[R6 Record, don't resolve]]). See [[Open questions]] in this vault for a working ledger.\n\nReplace the frontmatter above with this when you copy the template. A ready-made entry structure for the body follows it:\n\n```yaml\n---\ntitle: {{title}}\nupdated: {{date:YYYY-MM-DD}}\ntags: []\nstatus: to-confirm\nsummary: \"\"\nkeywords: []\nentities: []\nrelations: []\nlinks: []\nrev: \"\"\n---\n```\n\n```markdown\n## {{question}}\n\n- Version A — {{date}}, source: {{source}}. {{claim}}\n- Version B — {{date}}, source: {{source}}. {{claim}}\n\nConsequence: {{what changes depending on which version wins}}.\nOwner: {{who resolves it}}.\n```"},
{path:"templates/How to use these templates.md",title:"How to use these templates",type:"guide",tags:["template","guide"],updated:"2026-09-05",
 summary:"How to copy the templates folder into your own vault, point Obsidian's Templates plugin at it, and replace the placeholders by hand if you are not using Obsidian at all.",
 keywords:["how to use templates","copy templates folder","obsidian templates plugin","settings templates","placeholders by hand","no obsidian needed","getting started"],
 entities:[{name:"Mosaix Format",type:"project"},{name:"Obsidian",type:"tool"}],relations:[],links:["Template — note","Template — MOC","Template — synthesis","Template — document","Template — Conventions","Template — Open questions"],rev:"1a2b3c4d5e6f",status:"sourced",
 body:"Copy the `templates/` folder into your own vault, then start every new note from the matching file: [[Template — note]] for an ordinary note, [[Template — MOC]] for a map of content, [[Template — synthesis]] for a synthesis, [[Template — document]] for a composed document, [[Template — Conventions]] for the meta note, and [[Template — Open questions]] for the ledger.\n\nIn Obsidian, open Settings → Templates (the core Templates plugin), enable it, and set the template folder to `templates/`. Insert a template into a new note and Obsidian fills in `{{title}}` and `{{date:YYYY-MM-DD}}` for you; the `:YYYY-MM-DD` part is the plugin's date-format syntax, so keep it if you change the date shown.\n\nThe templates work without Obsidian too: open the file in any text editor, replace `{{title}}` with the note's title and `{{date:YYYY-MM-DD}}` with today's date, and fill in the rest by hand. Nothing here depends on any application beyond that."}
];
